version: '3.9'

services:
  node:
    build:
      context: ./docker/node
      dockerfile: ./Dockerfile
      target: base
      args:
        USER_NAME: node
        USER_ID: 1000
    command: '/bin/bash'
    stdin_open: true
    tty: true
    volumes:
      - .:/code
      - ~/.ssh:/home/node/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    profiles: ['node']

  mysql:
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: konrad

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
